// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9W0iABnTbnfGuJPnwMPtpdIxhJWLbhok',
    appId: '1:269319292485:web:ca43faa19e8e163f27c52c',
    messagingSenderId: '269319292485',
    projectId: 'todolistapp-c0fea',
    authDomain: 'todolistapp-c0fea.firebaseapp.com',
    storageBucket: 'todolistapp-c0fea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm_8Pd7cBLw0j8Sy071Z9_HgSo9_QDGkk',
    appId: '1:269319292485:android:4444bd09956a5c2a27c52c',
    messagingSenderId: '269319292485',
    projectId: 'todolistapp-c0fea',
    storageBucket: 'todolistapp-c0fea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9qPZD4BlWbKJZVUc9OT-6q8x07n275z0',
    appId: '1:269319292485:ios:2cb175e57813eedd27c52c',
    messagingSenderId: '269319292485',
    projectId: 'todolistapp-c0fea',
    storageBucket: 'todolistapp-c0fea.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9qPZD4BlWbKJZVUc9OT-6q8x07n275z0',
    appId: '1:269319292485:ios:2cb175e57813eedd27c52c',
    messagingSenderId: '269319292485',
    projectId: 'todolistapp-c0fea',
    storageBucket: 'todolistapp-c0fea.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9W0iABnTbnfGuJPnwMPtpdIxhJWLbhok',
    appId: '1:269319292485:web:fc9a47e8bb27261827c52c',
    messagingSenderId: '269319292485',
    projectId: 'todolistapp-c0fea',
    authDomain: 'todolistapp-c0fea.firebaseapp.com',
    storageBucket: 'todolistapp-c0fea.appspot.com',
  );
}
